version: '3'
services:
  telegram_bot:
    build: .
    environment:
      - BOT_TOKEN=6959137676:AAFOwrzfU4IL0EKj-hjCRCQSaWBhjS8TaYw
      - GROUP_ID=-4263977900
      - ADMINS_ID=972847950,996812211,640846280,732020026,1159695964
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: always
    volumes:
      - ./db.db:/app/db.db
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always